version: '3'

services:
  database:
    image: 'bitnami/postgresql:15.2.0'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignite-book-wise
    ports:
      - 5432:5432
